-- APIHub PostgreSQL v1 schema draft.
-- Target: PostgreSQL 15+.
-- UUID values are generated by the Go application (prefer UUIDv7).
-- Deliberately no foreign keys or CHECK constraints; ownership and associations
-- are validated by application services in the same transaction.

BEGIN;

CREATE TABLE IF NOT EXISTS schema_migrations (
    version bigint PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE schema_migrations IS 'APIHub PostgreSQL 迁移版本记录';
COMMENT ON COLUMN schema_migrations.version IS '单调递增的数据库迁移版本';
COMMENT ON COLUMN schema_migrations.applied_at IS '迁移成功提交时间';

CREATE TABLE workspaces (
    id uuid PRIMARY KEY,
    slug varchar(80) NOT NULL,
    name varchar(160) NOT NULL,
    status varchar(24) NOT NULL,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE workspaces IS '平台工作区；当前部署只创建一个工作区，用于替代旧 environment 边界';
COMMENT ON COLUMN workspaces.id IS '应用生成的工作区 UUID';
COMMENT ON COLUMN workspaces.slug IS 'URL 和日志使用的稳定工作区标识';
COMMENT ON COLUMN workspaces.name IS '页面展示的平台或组织名称';
COMMENT ON COLUMN workspaces.status IS '工作区状态，由应用校验 active 或 disabled';
COMMENT ON COLUMN workspaces.version IS '乐观锁版本号';
COMMENT ON COLUMN workspaces.created_at IS '创建时间';
COMMENT ON COLUMN workspaces.updated_at IS '最后更新时间';

CREATE UNIQUE INDEX workspaces_slug_uq ON workspaces (slug);

CREATE TABLE users (
    id uuid PRIMARY KEY,
    email varchar(320) NOT NULL,
    display_name varchar(160) NOT NULL,
    password_hash varchar(255),
    mfa_enabled boolean NOT NULL DEFAULT false,
    mfa_secret_blob bytea,
    status varchar(24) NOT NULL,
    auth_version bigint NOT NULL DEFAULT 1,
    last_login_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE users IS '平台登录用户和个人资料';
COMMENT ON COLUMN users.id IS '应用生成的用户 UUID';
COMMENT ON COLUMN users.email IS '登录邮箱，使用小写唯一索引';
COMMENT ON COLUMN users.display_name IS '用户显示名称';
COMMENT ON COLUMN users.password_hash IS '密码哈希；使用外部身份源时可以为空';
COMMENT ON COLUMN users.mfa_enabled IS '是否启用多因素认证';
COMMENT ON COLUMN users.mfa_secret_blob IS 'AES-GCM 加密后的 MFA 密钥';
COMMENT ON COLUMN users.status IS '用户状态，由应用校验 active、invited 或 disabled';
COMMENT ON COLUMN users.auth_version IS '密码、MFA 或全局登出后递增，用于失效旧会话';
COMMENT ON COLUMN users.last_login_at IS '最近成功登录时间';
COMMENT ON COLUMN users.created_at IS '创建时间';
COMMENT ON COLUMN users.updated_at IS '最后更新时间';

CREATE UNIQUE INDEX users_email_lower_uq ON users (lower(email));

CREATE TABLE user_sessions (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    token_hash char(64) NOT NULL,
    auth_version bigint NOT NULL,
    ip_address inet,
    user_agent varchar(512),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz
);

COMMENT ON TABLE user_sessions IS '管理端登录会话；Redis 只缓存，PostgreSQL 保存最终状态';
COMMENT ON COLUMN user_sessions.id IS '会话 UUID';
COMMENT ON COLUMN user_sessions.user_id IS '所属用户 UUID';
COMMENT ON COLUMN user_sessions.workspace_id IS '会话所属工作区 UUID';
COMMENT ON COLUMN user_sessions.token_hash IS '会话令牌 SHA-256 哈希，不保存明文';
COMMENT ON COLUMN user_sessions.auth_version IS '创建会话时的用户认证版本';
COMMENT ON COLUMN user_sessions.ip_address IS '创建会话时的客户端 IP';
COMMENT ON COLUMN user_sessions.user_agent IS '创建会话时的客户端 User-Agent';
COMMENT ON COLUMN user_sessions.expires_at IS '会话过期时间';
COMMENT ON COLUMN user_sessions.revoked_at IS '主动撤销时间';
COMMENT ON COLUMN user_sessions.created_at IS '创建时间';
COMMENT ON COLUMN user_sessions.last_used_at IS '最近使用时间';

CREATE UNIQUE INDEX user_sessions_token_hash_uq ON user_sessions (token_hash);
CREATE INDEX user_sessions_user_active_idx ON user_sessions (user_id, expires_at DESC) WHERE revoked_at IS NULL;

CREATE TABLE workspace_members (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role varchar(24) NOT NULL,
    status varchar(24) NOT NULL,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE workspace_members IS '团队成员及固定 RBAC 角色';
COMMENT ON COLUMN workspace_members.id IS '成员关系 UUID';
COMMENT ON COLUMN workspace_members.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN workspace_members.user_id IS '关联用户 UUID';
COMMENT ON COLUMN workspace_members.role IS '角色，由应用校验 owner、admin、developer 或 viewer';
COMMENT ON COLUMN workspace_members.status IS '成员状态，由应用校验 active 或 disabled';
COMMENT ON COLUMN workspace_members.version IS '乐观锁版本号';
COMMENT ON COLUMN workspace_members.created_at IS '加入时间';
COMMENT ON COLUMN workspace_members.updated_at IS '最后更新时间';

CREATE UNIQUE INDEX workspace_members_workspace_user_uq ON workspace_members (workspace_id, user_id);
CREATE INDEX workspace_members_workspace_role_idx ON workspace_members (workspace_id, role, status);

CREATE TABLE workspace_invitations (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    email varchar(320) NOT NULL,
    role varchar(24) NOT NULL,
    token_hash char(64) NOT NULL,
    invited_by uuid NOT NULL,
    expires_at timestamptz NOT NULL,
    accepted_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE workspace_invitations IS '团队成员一次性邀请';
COMMENT ON COLUMN workspace_invitations.id IS '邀请 UUID';
COMMENT ON COLUMN workspace_invitations.workspace_id IS '目标工作区 UUID';
COMMENT ON COLUMN workspace_invitations.email IS '受邀邮箱';
COMMENT ON COLUMN workspace_invitations.role IS '接受邀请后授予的固定角色';
COMMENT ON COLUMN workspace_invitations.token_hash IS '邀请令牌 SHA-256 哈希';
COMMENT ON COLUMN workspace_invitations.invited_by IS '发起邀请的用户 UUID';
COMMENT ON COLUMN workspace_invitations.expires_at IS '邀请过期时间';
COMMENT ON COLUMN workspace_invitations.accepted_at IS '接受时间';
COMMENT ON COLUMN workspace_invitations.revoked_at IS '撤销时间';
COMMENT ON COLUMN workspace_invitations.created_at IS '创建时间';

CREATE UNIQUE INDEX workspace_invitations_token_hash_uq ON workspace_invitations (token_hash);
CREATE INDEX workspace_invitations_pending_idx ON workspace_invitations (workspace_id, lower(email), expires_at DESC)
    WHERE accepted_at IS NULL AND revoked_at IS NULL;

CREATE TABLE system_groups (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    name varchar(100) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

COMMENT ON TABLE system_groups IS '系统目录分组';
COMMENT ON COLUMN system_groups.id IS '分组 UUID';
COMMENT ON COLUMN system_groups.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN system_groups.name IS '分组显示名称';
COMMENT ON COLUMN system_groups.sort_order IS '页面排序值，越小越靠前';
COMMENT ON COLUMN system_groups.created_at IS '创建时间';
COMMENT ON COLUMN system_groups.updated_at IS '最后更新时间';
COMMENT ON COLUMN system_groups.deleted_at IS '软删除时间';

CREATE UNIQUE INDEX system_groups_workspace_name_uq ON system_groups (workspace_id, name) WHERE deleted_at IS NULL;

CREATE TABLE systems (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    system_key varchar(100) NOT NULL,
    name varchar(160) NOT NULL,
    source varchar(24) NOT NULL,
    group_id uuid,
    description varchar(1000) NOT NULL DEFAULT '',
    homepage_url varchar(2048),
    icon_key varchar(255),
    status varchar(24) NOT NULL,
    catalog_version varchar(80),
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

COMMENT ON TABLE systems IS '内置公共平台和企业内部系统的统一目录';
COMMENT ON COLUMN systems.id IS '系统 UUID';
COMMENT ON COLUMN systems.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN systems.system_key IS '稳定系统标识，例如 github 或 internal-erp';
COMMENT ON COLUMN systems.name IS '系统显示名称';
COMMENT ON COLUMN systems.source IS '来源，由应用校验 builtin、imported 或 custom';
COMMENT ON COLUMN systems.group_id IS '系统分组 UUID';
COMMENT ON COLUMN systems.description IS '系统用途说明';
COMMENT ON COLUMN systems.homepage_url IS '系统官网或内部说明地址';
COMMENT ON COLUMN systems.icon_key IS '内置图标键或受控静态资源键';
COMMENT ON COLUMN systems.status IS '系统状态，由应用校验 active 或 disabled';
COMMENT ON COLUMN systems.catalog_version IS '导入目录版本，用于增量升级';
COMMENT ON COLUMN systems.version IS '乐观锁版本号';
COMMENT ON COLUMN systems.created_at IS '创建时间';
COMMENT ON COLUMN systems.updated_at IS '最后更新时间';
COMMENT ON COLUMN systems.deleted_at IS '软删除时间';

CREATE UNIQUE INDEX systems_workspace_key_uq ON systems (workspace_id, system_key) WHERE deleted_at IS NULL;
CREATE INDEX systems_workspace_group_idx ON systems (workspace_id, group_id, status) WHERE deleted_at IS NULL;

CREATE TABLE auth_templates (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    template_key varchar(100) NOT NULL,
    name varchar(160) NOT NULL,
    source varchar(24) NOT NULL,
    flow_type varchar(48) NOT NULL,
    status varchar(24) NOT NULL,
    credential_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
    token_request jsonb NOT NULL DEFAULT '{}'::jsonb,
    injection_rules jsonb NOT NULL DEFAULT '[]'::jsonb,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

COMMENT ON TABLE auth_templates IS '认证模板；定义字段、换 Token 规则和请求注入规则，不保存实际账号凭据';
COMMENT ON COLUMN auth_templates.id IS '认证模板 UUID';
COMMENT ON COLUMN auth_templates.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN auth_templates.template_key IS '稳定模板标识，例如 oauth2 或 erp-user-token';
COMMENT ON COLUMN auth_templates.name IS '模板显示名称';
COMMENT ON COLUMN auth_templates.source IS '模板来源，由应用校验 builtin 或 custom';
COMMENT ON COLUMN auth_templates.flow_type IS '认证流程类型，例如 static、oauth2_code、password_token 或 client_credentials';
COMMENT ON COLUMN auth_templates.status IS '模板状态，由应用校验 draft、published 或 disabled';
COMMENT ON COLUMN auth_templates.credential_schema IS '连接账号需要填写的字段定义及敏感标记';
COMMENT ON COLUMN auth_templates.token_request IS '换取和刷新 Token 的受控 HTTP 请求模板';
COMMENT ON COLUMN auth_templates.injection_rules IS 'Header、Query 或 Body 的凭据注入规则数组';
COMMENT ON COLUMN auth_templates.version IS '乐观锁版本号';
COMMENT ON COLUMN auth_templates.created_at IS '创建时间';
COMMENT ON COLUMN auth_templates.updated_at IS '最后更新时间';
COMMENT ON COLUMN auth_templates.deleted_at IS '软删除时间';

CREATE UNIQUE INDEX auth_templates_workspace_key_uq ON auth_templates (workspace_id, template_key) WHERE deleted_at IS NULL;
CREATE INDEX auth_templates_workspace_status_idx ON auth_templates (workspace_id, status, updated_at DESC);

CREATE TABLE system_auth_templates (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    system_id uuid NOT NULL,
    auth_template_id uuid NOT NULL,
    is_default boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE system_auth_templates IS '系统允许使用的认证模板兼容关系';
COMMENT ON COLUMN system_auth_templates.id IS '兼容关系 UUID';
COMMENT ON COLUMN system_auth_templates.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN system_auth_templates.system_id IS '系统 UUID';
COMMENT ON COLUMN system_auth_templates.auth_template_id IS '认证模板 UUID';
COMMENT ON COLUMN system_auth_templates.is_default IS '是否为该系统新建认证实例时的默认模板';
COMMENT ON COLUMN system_auth_templates.created_at IS '创建时间';

CREATE UNIQUE INDEX system_auth_templates_pair_uq ON system_auth_templates (workspace_id, system_id, auth_template_id);
CREATE UNIQUE INDEX system_auth_templates_default_uq ON system_auth_templates (workspace_id, system_id) WHERE is_default;

CREATE TABLE auth_instances (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    instance_key varchar(100) NOT NULL,
    name varchar(160) NOT NULL,
    system_id uuid NOT NULL,
    auth_template_id uuid NOT NULL,
    status varchar(24) NOT NULL,
    token_url varchar(2048),
    refresh_url varchar(2048),
    token_path varchar(255),
    expiry_path varchar(255),
    header_name varchar(255),
    header_value_template varchar(1000),
    public_config jsonb NOT NULL DEFAULT '{}'::jsonb,
    secret_blob bytea,
    key_version smallint NOT NULL DEFAULT 1,
    version bigint NOT NULL DEFAULT 1,
    last_tested_at timestamptz,
    last_test_status varchar(24),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

COMMENT ON TABLE auth_instances IS '基于模板创建的具体系统认证实例；一个实例只能属于一个系统';
COMMENT ON COLUMN auth_instances.id IS '认证实例 UUID';
COMMENT ON COLUMN auth_instances.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN auth_instances.instance_key IS '供系统和集成稳定引用的实例标识';
COMMENT ON COLUMN auth_instances.name IS '认证实例显示名称';
COMMENT ON COLUMN auth_instances.system_id IS '实例唯一所属的系统 UUID';
COMMENT ON COLUMN auth_instances.auth_template_id IS '实例采用的认证模板 UUID';
COMMENT ON COLUMN auth_instances.status IS '实例状态，由应用校验 ready、draft 或 disabled';
COMMENT ON COLUMN auth_instances.token_url IS '登录或换取访问令牌的地址';
COMMENT ON COLUMN auth_instances.refresh_url IS '刷新访问令牌的地址';
COMMENT ON COLUMN auth_instances.token_path IS '从响应 JSON 提取访问令牌的路径';
COMMENT ON COLUMN auth_instances.expiry_path IS '从响应 JSON 提取有效期的路径';
COMMENT ON COLUMN auth_instances.header_name IS '调用系统接口时注入的 Header 名称';
COMMENT ON COLUMN auth_instances.header_value_template IS '调用系统接口时注入的 Header 值模板';
COMMENT ON COLUMN auth_instances.public_config IS 'OAuth scopes、请求格式等非敏感实例配置';
COMMENT ON COLUMN auth_instances.secret_blob IS 'AES-GCM 加密后的 OAuth App 密钥、证书引用等系统级秘密';
COMMENT ON COLUMN auth_instances.key_version IS '加密主密钥版本';
COMMENT ON COLUMN auth_instances.version IS '乐观锁及密文 AAD 版本';
COMMENT ON COLUMN auth_instances.last_tested_at IS '最近一次实例连通性测试时间';
COMMENT ON COLUMN auth_instances.last_test_status IS '最近测试状态';
COMMENT ON COLUMN auth_instances.created_at IS '创建时间';
COMMENT ON COLUMN auth_instances.updated_at IS '最后更新时间';
COMMENT ON COLUMN auth_instances.deleted_at IS '软删除时间';

CREATE UNIQUE INDEX auth_instances_workspace_key_uq ON auth_instances (workspace_id, instance_key) WHERE deleted_at IS NULL;
CREATE INDEX auth_instances_system_status_idx ON auth_instances (workspace_id, system_id, status) WHERE deleted_at IS NULL;

CREATE TABLE integrations (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    integration_key varchar(100) NOT NULL,
    name varchar(160) NOT NULL,
    system_id uuid NOT NULL,
    auth_instance_id uuid NOT NULL,
    base_url varchar(2048) NOT NULL,
    status varchar(24) NOT NULL,
    settings jsonb NOT NULL DEFAULT '{}'::jsonb,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

COMMENT ON TABLE integrations IS '系统在当前工作区中的可调用配置实例';
COMMENT ON COLUMN integrations.id IS '集成 UUID';
COMMENT ON COLUMN integrations.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN integrations.integration_key IS '稳定集成标识';
COMMENT ON COLUMN integrations.name IS '集成显示名称';
COMMENT ON COLUMN integrations.system_id IS '目标系统 UUID';
COMMENT ON COLUMN integrations.auth_instance_id IS '该集成采用的认证实例 UUID';
COMMENT ON COLUMN integrations.base_url IS '由服务端信任并经过 SSRF 校验的 API 基础地址';
COMMENT ON COLUMN integrations.status IS '集成状态，由应用校验 ready、draft 或 disabled';
COMMENT ON COLUMN integrations.settings IS '分页、区域和系统专属非敏感设置';
COMMENT ON COLUMN integrations.version IS '乐观锁版本号';
COMMENT ON COLUMN integrations.created_at IS '创建时间';
COMMENT ON COLUMN integrations.updated_at IS '最后更新时间';
COMMENT ON COLUMN integrations.deleted_at IS '软删除时间';

CREATE UNIQUE INDEX integrations_workspace_key_uq ON integrations (workspace_id, integration_key) WHERE deleted_at IS NULL;
CREATE INDEX integrations_system_status_idx ON integrations (workspace_id, system_id, status) WHERE deleted_at IS NULL;

CREATE TABLE end_users (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    external_key varchar(255) NOT NULL,
    display_name varchar(160),
    email varchar(320),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE end_users IS '外部系统连接所代表的最终用户、租户或服务账号主体';
COMMENT ON COLUMN end_users.id IS '最终用户 UUID';
COMMENT ON COLUMN end_users.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN end_users.external_key IS '调用方提供的稳定主体标识';
COMMENT ON COLUMN end_users.display_name IS '页面显示名称';
COMMENT ON COLUMN end_users.email IS '可选联系邮箱';
COMMENT ON COLUMN end_users.metadata IS '非敏感业务标签';
COMMENT ON COLUMN end_users.created_at IS '创建时间';
COMMENT ON COLUMN end_users.updated_at IS '最后更新时间';

CREATE UNIQUE INDEX end_users_workspace_external_key_uq ON end_users (workspace_id, external_key);

CREATE TABLE connections (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    connection_key varchar(100) NOT NULL,
    name varchar(160) NOT NULL,
    integration_id uuid NOT NULL,
    auth_instance_id uuid NOT NULL,
    end_user_id uuid NOT NULL,
    status varchar(24) NOT NULL,
    credential_blob bytea NOT NULL,
    key_version smallint NOT NULL DEFAULT 1,
    revision bigint NOT NULL DEFAULT 1,
    token_expires_at timestamptz,
    last_verified_at timestamptz,
    last_used_at timestamptz,
    last_error_code varchar(100),
    last_error_message varchar(2000),
    tags varchar(80)[] NOT NULL DEFAULT '{}'::varchar[],
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

COMMENT ON TABLE connections IS '集成下的连接账号及加密凭据';
COMMENT ON COLUMN connections.id IS '连接账号 UUID';
COMMENT ON COLUMN connections.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN connections.connection_key IS '运行 API 使用的稳定连接标识';
COMMENT ON COLUMN connections.name IS '连接账号显示名称';
COMMENT ON COLUMN connections.integration_id IS '所属集成 UUID';
COMMENT ON COLUMN connections.auth_instance_id IS '认证实例 UUID';
COMMENT ON COLUMN connections.end_user_id IS '最终用户、租户或服务账号 UUID';
COMMENT ON COLUMN connections.status IS '连接状态，由应用校验 pending、active、expired、error 或 revoked';
COMMENT ON COLUMN connections.credential_blob IS 'AES-GCM 加密后的账号凭据、Token 和 refresh token';
COMMENT ON COLUMN connections.key_version IS '加密主密钥版本';
COMMENT ON COLUMN connections.revision IS '刷新 Token 和编辑凭据使用的 CAS 版本及密文 AAD 版本';
COMMENT ON COLUMN connections.token_expires_at IS '访问令牌过期时间';
COMMENT ON COLUMN connections.last_verified_at IS '最近一次认证验证成功时间';
COMMENT ON COLUMN connections.last_used_at IS '最近一次实际调用时间';
COMMENT ON COLUMN connections.last_error_code IS '最近认证错误代码';
COMMENT ON COLUMN connections.last_error_message IS '最近认证错误的脱敏摘要';
COMMENT ON COLUMN connections.tags IS '页面筛选使用的短标签数组';
COMMENT ON COLUMN connections.created_at IS '创建时间';
COMMENT ON COLUMN connections.updated_at IS '最后更新时间';
COMMENT ON COLUMN connections.deleted_at IS '软删除时间';

CREATE UNIQUE INDEX connections_workspace_key_uq ON connections (workspace_id, connection_key) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX connections_integration_name_uq ON connections (workspace_id, integration_id, name) WHERE deleted_at IS NULL;
CREATE INDEX connections_integration_status_idx ON connections (workspace_id, integration_id, status) WHERE deleted_at IS NULL;
CREATE INDEX connections_end_user_idx ON connections (workspace_id, end_user_id, updated_at DESC) WHERE deleted_at IS NULL;

CREATE TABLE actions (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    action_key varchar(180) NOT NULL,
    name varchar(180) NOT NULL,
    description varchar(1000) NOT NULL DEFAULT '',
    source varchar(24) NOT NULL,
    system_id uuid NOT NULL,
    integration_id uuid,
    http_method varchar(12) NOT NULL,
    relative_path varchar(2000) NOT NULL,
    required_scopes varchar(255)[] NOT NULL DEFAULT '{}'::varchar[],
    input_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
    output_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
    example_input jsonb NOT NULL DEFAULT '{}'::jsonb,
    executable boolean NOT NULL DEFAULT false,
    status varchar(24) NOT NULL,
    catalog_version varchar(80),
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

COMMENT ON TABLE actions IS '系统内置和企业自定义 API 操作定义';
COMMENT ON COLUMN actions.id IS '操作 UUID';
COMMENT ON COLUMN actions.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN actions.action_key IS '运行 API 使用的稳定操作标识，例如 github.create_issue';
COMMENT ON COLUMN actions.name IS '操作显示名称';
COMMENT ON COLUMN actions.description IS '操作用途说明';
COMMENT ON COLUMN actions.source IS '来源，由应用校验 builtin、imported 或 custom';
COMMENT ON COLUMN actions.system_id IS '所属系统 UUID';
COMMENT ON COLUMN actions.integration_id IS '自定义操作固定所属集成；内置操作可以为空';
COMMENT ON COLUMN actions.http_method IS '受支持的 HTTP 方法';
COMMENT ON COLUMN actions.relative_path IS '相对 API 路径，禁止绝对 URL';
COMMENT ON COLUMN actions.required_scopes IS '系统侧要求的权限范围';
COMMENT ON COLUMN actions.input_schema IS 'JSON Schema 输入定义';
COMMENT ON COLUMN actions.output_schema IS 'JSON Schema 输出定义';
COMMENT ON COLUMN actions.example_input IS '页面验证使用的输入示例';
COMMENT ON COLUMN actions.executable IS '当前 Go 执行器是否真正支持该操作';
COMMENT ON COLUMN actions.status IS '操作状态，由应用校验 active、draft 或 disabled';
COMMENT ON COLUMN actions.catalog_version IS '导入目录版本';
COMMENT ON COLUMN actions.version IS '乐观锁版本号';
COMMENT ON COLUMN actions.created_at IS '创建时间';
COMMENT ON COLUMN actions.updated_at IS '最后更新时间';
COMMENT ON COLUMN actions.deleted_at IS '软删除时间';

CREATE UNIQUE INDEX actions_workspace_key_uq ON actions (workspace_id, action_key) WHERE deleted_at IS NULL;
CREATE INDEX actions_system_status_idx ON actions (workspace_id, system_id, status) WHERE deleted_at IS NULL;
CREATE INDEX actions_integration_idx ON actions (workspace_id, integration_id) WHERE integration_id IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE runtime_tokens (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    name varchar(160) NOT NULL,
    token_prefix varchar(24) NOT NULL,
    token_hash char(64) NOT NULL,
    status varchar(24) NOT NULL,
    expires_at timestamptz,
    last_used_at timestamptz,
    revoked_at timestamptz,
    created_by uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE runtime_tokens IS '运行 API 使用的机器令牌；明文只在创建时返回一次';
COMMENT ON COLUMN runtime_tokens.id IS '运行时令牌 UUID';
COMMENT ON COLUMN runtime_tokens.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN runtime_tokens.name IS '令牌显示名称';
COMMENT ON COLUMN runtime_tokens.token_prefix IS '页面辨识令牌使用的非敏感前缀';
COMMENT ON COLUMN runtime_tokens.token_hash IS '令牌 SHA-256 哈希';
COMMENT ON COLUMN runtime_tokens.status IS '令牌状态，由应用校验 active 或 revoked';
COMMENT ON COLUMN runtime_tokens.expires_at IS '可选过期时间';
COMMENT ON COLUMN runtime_tokens.last_used_at IS '最近使用时间';
COMMENT ON COLUMN runtime_tokens.revoked_at IS '撤销时间';
COMMENT ON COLUMN runtime_tokens.created_by IS '创建令牌的用户 UUID';
COMMENT ON COLUMN runtime_tokens.created_at IS '创建时间';

CREATE UNIQUE INDEX runtime_tokens_hash_uq ON runtime_tokens (token_hash);
CREATE INDEX runtime_tokens_workspace_created_idx ON runtime_tokens (workspace_id, created_at DESC);

CREATE TABLE runtime_token_action_rules (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    runtime_token_id uuid NOT NULL,
    effect varchar(16) NOT NULL,
    action_pattern varchar(255) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE runtime_token_action_rules IS '运行时令牌的操作 allow 或 deny 规则，deny 始终优先';
COMMENT ON COLUMN runtime_token_action_rules.id IS '策略规则 UUID';
COMMENT ON COLUMN runtime_token_action_rules.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN runtime_token_action_rules.runtime_token_id IS '运行时令牌 UUID';
COMMENT ON COLUMN runtime_token_action_rules.effect IS '规则效果，由应用校验 allow 或 deny';
COMMENT ON COLUMN runtime_token_action_rules.action_pattern IS '操作匹配模式，例如 github.*';
COMMENT ON COLUMN runtime_token_action_rules.created_at IS '创建时间';

CREATE UNIQUE INDEX runtime_token_action_rules_uq ON runtime_token_action_rules (workspace_id, runtime_token_id, effect, action_pattern);

CREATE TABLE runtime_token_connection_grants (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    runtime_token_id uuid NOT NULL,
    connection_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE runtime_token_connection_grants IS '运行时令牌允许使用的连接账号白名单';
COMMENT ON COLUMN runtime_token_connection_grants.id IS '连接授权 UUID';
COMMENT ON COLUMN runtime_token_connection_grants.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN runtime_token_connection_grants.runtime_token_id IS '运行时令牌 UUID';
COMMENT ON COLUMN runtime_token_connection_grants.connection_id IS '允许访问的连接账号 UUID';
COMMENT ON COLUMN runtime_token_connection_grants.created_at IS '创建时间';

CREATE UNIQUE INDEX runtime_token_connection_grants_uq ON runtime_token_connection_grants (workspace_id, runtime_token_id, connection_id);

CREATE TABLE sync_tasks (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    task_key varchar(120) NOT NULL,
    name varchar(180) NOT NULL,
    integration_id uuid NOT NULL,
    connection_id uuid NOT NULL,
    action_id uuid NOT NULL,
    status varchar(24) NOT NULL,
    schedule_type varchar(24) NOT NULL,
    cron_expression varchar(120),
    schedule_timezone varchar(80) NOT NULL DEFAULT 'UTC',
    next_run_at timestamptz,
    retry_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
    input jsonb NOT NULL DEFAULT '{}'::jsonb,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

COMMENT ON TABLE sync_tasks IS '定时或手动运行的增量同步任务';
COMMENT ON COLUMN sync_tasks.id IS '同步任务 UUID';
COMMENT ON COLUMN sync_tasks.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN sync_tasks.task_key IS '稳定任务标识';
COMMENT ON COLUMN sync_tasks.name IS '任务显示名称';
COMMENT ON COLUMN sync_tasks.integration_id IS '所属集成 UUID';
COMMENT ON COLUMN sync_tasks.connection_id IS '任务执行使用的连接账号 UUID';
COMMENT ON COLUMN sync_tasks.action_id IS '负责拉取分页数据的操作 UUID';
COMMENT ON COLUMN sync_tasks.status IS '任务状态，由应用校验 draft、deployed、paused 或 disabled';
COMMENT ON COLUMN sync_tasks.schedule_type IS '调度类型，由应用校验 cron 或 manual';
COMMENT ON COLUMN sync_tasks.cron_expression IS '标准 cron 表达式；手动任务为空';
COMMENT ON COLUMN sync_tasks.schedule_timezone IS 'IANA 时区名称';
COMMENT ON COLUMN sync_tasks.next_run_at IS 'scheduler 下一次扫描时间';
COMMENT ON COLUMN sync_tasks.retry_policy IS '最大次数和退避参数';
COMMENT ON COLUMN sync_tasks.input IS '同步操作的固定输入参数';
COMMENT ON COLUMN sync_tasks.version IS '乐观锁版本号';
COMMENT ON COLUMN sync_tasks.created_at IS '创建时间';
COMMENT ON COLUMN sync_tasks.updated_at IS '最后更新时间';
COMMENT ON COLUMN sync_tasks.deleted_at IS '软删除时间';

CREATE UNIQUE INDEX sync_tasks_workspace_key_uq ON sync_tasks (workspace_id, task_key) WHERE deleted_at IS NULL;
CREATE INDEX sync_tasks_due_idx ON sync_tasks (next_run_at, id) WHERE status = 'deployed' AND deleted_at IS NULL;

CREATE TABLE sync_task_states (
    sync_task_id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    checkpoint jsonb NOT NULL DEFAULT '{}'::jsonb,
    checkpoint_version bigint NOT NULL DEFAULT 0,
    last_operation_id uuid,
    last_success_at timestamptz,
    last_error_at timestamptz,
    records_seen bigint NOT NULL DEFAULT 0,
    records_active bigint NOT NULL DEFAULT 0,
    records_deleted bigint NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE sync_task_states IS '同步任务的增量检查点和累计计数';
COMMENT ON COLUMN sync_task_states.sync_task_id IS '同步任务 UUID，同时作为主键';
COMMENT ON COLUMN sync_task_states.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN sync_task_states.checkpoint IS '由同步适配器定义的游标或增量水位';
COMMENT ON COLUMN sync_task_states.checkpoint_version IS '提交检查点使用的 CAS 版本';
COMMENT ON COLUMN sync_task_states.last_operation_id IS '最近一次运行 UUID';
COMMENT ON COLUMN sync_task_states.last_success_at IS '最近成功时间';
COMMENT ON COLUMN sync_task_states.last_error_at IS '最近失败时间';
COMMENT ON COLUMN sync_task_states.records_seen IS '累计读取记录数量';
COMMENT ON COLUMN sync_task_states.records_active IS '当前有效记录数量';
COMMENT ON COLUMN sync_task_states.records_deleted IS '已标记删除记录数量';
COMMENT ON COLUMN sync_task_states.updated_at IS '最后更新时间';

CREATE INDEX sync_task_states_workspace_updated_idx ON sync_task_states (workspace_id, updated_at DESC);

CREATE TABLE sync_records (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    sync_task_id uuid NOT NULL,
    model varchar(120) NOT NULL,
    external_id varchar(512) NOT NULL,
    payload jsonb NOT NULL,
    payload_hash char(64) NOT NULL,
    source_created_at timestamptz,
    source_updated_at timestamptz,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

COMMENT ON TABLE sync_records IS '同步任务拉取的规范化外部记录';
COMMENT ON COLUMN sync_records.id IS '同步记录 UUID';
COMMENT ON COLUMN sync_records.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN sync_records.sync_task_id IS '所属同步任务 UUID';
COMMENT ON COLUMN sync_records.model IS '数据模型名称，例如 Issue 或 Account';
COMMENT ON COLUMN sync_records.external_id IS '外部系统记录稳定 ID';
COMMENT ON COLUMN sync_records.payload IS '外部记录 JSON 内容';
COMMENT ON COLUMN sync_records.payload_hash IS '规范化 payload 的 SHA-256，用于跳过无变化更新';
COMMENT ON COLUMN sync_records.source_created_at IS '外部系统记录创建时间';
COMMENT ON COLUMN sync_records.source_updated_at IS '外部系统记录更新时间';
COMMENT ON COLUMN sync_records.first_seen_at IS '首次同步到本平台的时间';
COMMENT ON COLUMN sync_records.last_seen_at IS '最近一次同步确认存在的时间';
COMMENT ON COLUMN sync_records.deleted_at IS '外部删除或 full sync 缺失后的标记时间';

CREATE UNIQUE INDEX sync_records_task_model_external_uq ON sync_records (workspace_id, sync_task_id, model, external_id);
CREATE INDEX sync_records_task_updated_idx ON sync_records (workspace_id, sync_task_id, source_updated_at DESC, id DESC);
CREATE INDEX sync_records_payload_gin_idx ON sync_records USING gin (payload jsonb_path_ops);

CREATE TABLE jobs (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    kind varchar(32) NOT NULL,
    resource_id uuid,
    operation_id uuid,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    status varchar(24) NOT NULL,
    priority smallint NOT NULL DEFAULT 0,
    attempt integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 8,
    run_after timestamptz NOT NULL DEFAULT now(),
    lease_owner varchar(160),
    lease_expires_at timestamptz,
    last_error varchar(2000),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz
);

COMMENT ON TABLE jobs IS 'PostgreSQL 可靠任务队列，供同步、认证刷新和 Webhook worker 使用';
COMMENT ON COLUMN jobs.id IS '任务 UUID';
COMMENT ON COLUMN jobs.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN jobs.kind IS '任务类型，例如 sync_run、auth_refresh 或 webhook_delivery';
COMMENT ON COLUMN jobs.resource_id IS '任务对应的业务资源 UUID';
COMMENT ON COLUMN jobs.operation_id IS '统一运行记录 UUID';
COMMENT ON COLUMN jobs.payload IS '任务参数，不允许保存明文凭据';
COMMENT ON COLUMN jobs.status IS '任务状态，由应用校验 queued、running、succeeded、failed、cancelled 或 dead';
COMMENT ON COLUMN jobs.priority IS '任务优先级，数值越大越先执行';
COMMENT ON COLUMN jobs.attempt IS '已经开始的执行次数';
COMMENT ON COLUMN jobs.max_attempts IS '最大执行次数';
COMMENT ON COLUMN jobs.run_after IS '下一次允许执行时间';
COMMENT ON COLUMN jobs.lease_owner IS '当前 worker 实例标识';
COMMENT ON COLUMN jobs.lease_expires_at IS '租约过期时间，过期任务可以被重新领取';
COMMENT ON COLUMN jobs.last_error IS '最近一次失败的脱敏摘要';
COMMENT ON COLUMN jobs.created_at IS '创建时间';
COMMENT ON COLUMN jobs.updated_at IS '最后更新时间';
COMMENT ON COLUMN jobs.completed_at IS '最终完成时间';

CREATE INDEX jobs_claim_idx ON jobs (priority DESC, run_after, id) WHERE status = 'queued';
CREATE INDEX jobs_lease_recovery_idx ON jobs (lease_expires_at, id) WHERE status = 'running';
CREATE INDEX jobs_resource_idx ON jobs (workspace_id, kind, resource_id, created_at DESC);

CREATE TABLE webhook_endpoints (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    name varchar(160) NOT NULL,
    primary_url varchar(2048) NOT NULL,
    fallback_url varchar(2048),
    secret_blob bytea NOT NULL,
    key_version smallint NOT NULL DEFAULT 1,
    status varchar(24) NOT NULL,
    failure_count integer NOT NULL DEFAULT 0,
    paused_at timestamptz,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

COMMENT ON TABLE webhook_endpoints IS '平台事件的出站 Webhook 目标和签名配置';
COMMENT ON COLUMN webhook_endpoints.id IS 'Webhook 端点 UUID';
COMMENT ON COLUMN webhook_endpoints.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN webhook_endpoints.name IS '端点显示名称';
COMMENT ON COLUMN webhook_endpoints.primary_url IS '主要投递地址';
COMMENT ON COLUMN webhook_endpoints.fallback_url IS '主要地址失败后的备用地址';
COMMENT ON COLUMN webhook_endpoints.secret_blob IS 'AES-GCM 加密的 HMAC 签名密钥';
COMMENT ON COLUMN webhook_endpoints.key_version IS '加密主密钥版本';
COMMENT ON COLUMN webhook_endpoints.status IS '端点状态，由应用校验 active、paused 或 disabled';
COMMENT ON COLUMN webhook_endpoints.failure_count IS '连续失败次数';
COMMENT ON COLUMN webhook_endpoints.paused_at IS '自动或手动暂停时间';
COMMENT ON COLUMN webhook_endpoints.version IS '乐观锁版本号';
COMMENT ON COLUMN webhook_endpoints.created_at IS '创建时间';
COMMENT ON COLUMN webhook_endpoints.updated_at IS '最后更新时间';
COMMENT ON COLUMN webhook_endpoints.deleted_at IS '软删除时间';

CREATE INDEX webhook_endpoints_workspace_status_idx ON webhook_endpoints (workspace_id, status) WHERE deleted_at IS NULL;

CREATE TABLE webhook_endpoint_events (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    webhook_endpoint_id uuid NOT NULL,
    event_pattern varchar(160) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE webhook_endpoint_events IS '出站 Webhook 端点订阅的事件模式';
COMMENT ON COLUMN webhook_endpoint_events.id IS '订阅关系 UUID';
COMMENT ON COLUMN webhook_endpoint_events.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN webhook_endpoint_events.webhook_endpoint_id IS 'Webhook 端点 UUID';
COMMENT ON COLUMN webhook_endpoint_events.event_pattern IS '事件模式，例如 auth.*、connection.* 或 sync.completed';
COMMENT ON COLUMN webhook_endpoint_events.created_at IS '创建时间';

CREATE UNIQUE INDEX webhook_endpoint_events_uq ON webhook_endpoint_events (workspace_id, webhook_endpoint_id, event_pattern);

CREATE TABLE webhook_sources (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    source_key varchar(100) NOT NULL,
    name varchar(160) NOT NULL,
    integration_id uuid NOT NULL,
    status varchar(24) NOT NULL,
    signature_type varchar(48) NOT NULL,
    secret_blob bytea,
    key_version smallint NOT NULL DEFAULT 1,
    subscribed_events varchar(160)[] NOT NULL DEFAULT '{}'::varchar[],
    settings jsonb NOT NULL DEFAULT '{}'::jsonb,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

COMMENT ON TABLE webhook_sources IS '外部系统入站 Webhook 入口及签名验证配置';
COMMENT ON COLUMN webhook_sources.id IS '入站源 UUID';
COMMENT ON COLUMN webhook_sources.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN webhook_sources.source_key IS '公开路径使用的不可猜测稳定标识';
COMMENT ON COLUMN webhook_sources.name IS '入站源显示名称';
COMMENT ON COLUMN webhook_sources.integration_id IS '所属集成 UUID';
COMMENT ON COLUMN webhook_sources.status IS '入站源状态，由应用校验 active 或 disabled';
COMMENT ON COLUMN webhook_sources.signature_type IS '提供商签名验证类型';
COMMENT ON COLUMN webhook_sources.secret_blob IS 'AES-GCM 加密后的 Webhook 验签秘密';
COMMENT ON COLUMN webhook_sources.key_version IS '加密主密钥版本';
COMMENT ON COLUMN webhook_sources.subscribed_events IS '允许接收的提供商事件类型';
COMMENT ON COLUMN webhook_sources.settings IS '提供商验签和事件映射的非敏感设置';
COMMENT ON COLUMN webhook_sources.version IS '乐观锁版本号';
COMMENT ON COLUMN webhook_sources.created_at IS '创建时间';
COMMENT ON COLUMN webhook_sources.updated_at IS '最后更新时间';
COMMENT ON COLUMN webhook_sources.deleted_at IS '软删除时间';

CREATE UNIQUE INDEX webhook_sources_workspace_key_uq ON webhook_sources (workspace_id, source_key) WHERE deleted_at IS NULL;
CREATE INDEX webhook_sources_integration_idx ON webhook_sources (workspace_id, integration_id, status) WHERE deleted_at IS NULL;

CREATE TABLE webhook_ingress_events (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    webhook_source_id uuid NOT NULL,
    provider_event_id varchar(512) NOT NULL,
    event_type varchar(160) NOT NULL,
    payload jsonb NOT NULL,
    status varchar(24) NOT NULL,
    operation_id uuid,
    received_at timestamptz NOT NULL DEFAULT now(),
    processed_at timestamptz,
    expires_at timestamptz NOT NULL
);

COMMENT ON TABLE webhook_ingress_events IS '入站 Webhook 验签后的去重记录和受限事件内容';
COMMENT ON COLUMN webhook_ingress_events.id IS '入站事件 UUID';
COMMENT ON COLUMN webhook_ingress_events.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN webhook_ingress_events.webhook_source_id IS '入站源 UUID';
COMMENT ON COLUMN webhook_ingress_events.provider_event_id IS '提供商事件 ID 或请求体哈希';
COMMENT ON COLUMN webhook_ingress_events.event_type IS '规范化事件类型';
COMMENT ON COLUMN webhook_ingress_events.payload IS '经过大小限制和敏感字段处理的事件 JSON';
COMMENT ON COLUMN webhook_ingress_events.status IS '处理状态，由应用校验 received、processed、ignored 或 failed';
COMMENT ON COLUMN webhook_ingress_events.operation_id IS '关联的统一运行记录 UUID';
COMMENT ON COLUMN webhook_ingress_events.received_at IS '接收时间';
COMMENT ON COLUMN webhook_ingress_events.processed_at IS '处理完成时间';
COMMENT ON COLUMN webhook_ingress_events.expires_at IS '去重和内容保留到期时间';

CREATE UNIQUE INDEX webhook_ingress_events_dedupe_uq ON webhook_ingress_events (workspace_id, webhook_source_id, provider_event_id);
CREATE INDEX webhook_ingress_events_received_idx ON webhook_ingress_events (workspace_id, received_at DESC, id DESC);

CREATE TABLE outbox_events (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    event_type varchar(160) NOT NULL,
    aggregate_type varchar(80) NOT NULL,
    aggregate_id uuid NOT NULL,
    dedupe_key varchar(255) NOT NULL,
    payload jsonb NOT NULL,
    status varchar(24) NOT NULL DEFAULT 'pending',
    available_at timestamptz NOT NULL DEFAULT now(),
    attempt integer NOT NULL DEFAULT 0,
    lease_owner varchar(160),
    lease_expires_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    published_at timestamptz
);

COMMENT ON TABLE outbox_events IS '与业务写入同事务提交的可靠平台事件';
COMMENT ON COLUMN outbox_events.id IS '事件 UUID，同时作为对外 event id';
COMMENT ON COLUMN outbox_events.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN outbox_events.event_type IS '规范化事件类型';
COMMENT ON COLUMN outbox_events.aggregate_type IS '产生事件的资源类型';
COMMENT ON COLUMN outbox_events.aggregate_id IS '产生事件的资源 UUID';
COMMENT ON COLUMN outbox_events.dedupe_key IS '业务生成的幂等键';
COMMENT ON COLUMN outbox_events.payload IS '出站事件数据，不包含明文凭据';
COMMENT ON COLUMN outbox_events.status IS '发布状态，由应用校验 pending、publishing、published 或 dead';
COMMENT ON COLUMN outbox_events.available_at IS '允许 dispatcher 处理的时间';
COMMENT ON COLUMN outbox_events.attempt IS '发布尝试次数';
COMMENT ON COLUMN outbox_events.lease_owner IS '当前 dispatcher 实例标识';
COMMENT ON COLUMN outbox_events.lease_expires_at IS '发布租约过期时间';
COMMENT ON COLUMN outbox_events.created_at IS '创建时间';
COMMENT ON COLUMN outbox_events.published_at IS '完成端点展开的时间';

CREATE UNIQUE INDEX outbox_events_workspace_dedupe_uq ON outbox_events (workspace_id, dedupe_key);
CREATE INDEX outbox_events_claim_idx ON outbox_events (available_at, id) WHERE status = 'pending';

CREATE TABLE webhook_deliveries (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    outbox_event_id uuid NOT NULL,
    webhook_endpoint_id uuid NOT NULL,
    target_url varchar(2048) NOT NULL,
    status varchar(24) NOT NULL,
    attempt_count integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz,
    last_http_status integer,
    last_error varchar(2000),
    created_at timestamptz NOT NULL DEFAULT now(),
    delivered_at timestamptz,
    dead_at timestamptz
);

COMMENT ON TABLE webhook_deliveries IS '一个 outbox 事件到一个出站端点的投递状态';
COMMENT ON COLUMN webhook_deliveries.id IS '投递 UUID';
COMMENT ON COLUMN webhook_deliveries.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN webhook_deliveries.outbox_event_id IS '平台 outbox 事件 UUID';
COMMENT ON COLUMN webhook_deliveries.webhook_endpoint_id IS '目标 Webhook 端点 UUID';
COMMENT ON COLUMN webhook_deliveries.target_url IS '本次投递使用的主地址或备用地址快照';
COMMENT ON COLUMN webhook_deliveries.status IS '投递状态，由应用校验 pending、retrying、delivered 或 dead';
COMMENT ON COLUMN webhook_deliveries.attempt_count IS '已经完成的 HTTP 尝试次数';
COMMENT ON COLUMN webhook_deliveries.next_attempt_at IS '下一次重试时间';
COMMENT ON COLUMN webhook_deliveries.last_http_status IS '最近一次目标 HTTP 状态码';
COMMENT ON COLUMN webhook_deliveries.last_error IS '最近一次投递错误摘要';
COMMENT ON COLUMN webhook_deliveries.created_at IS '创建时间';
COMMENT ON COLUMN webhook_deliveries.delivered_at IS '成功投递时间';
COMMENT ON COLUMN webhook_deliveries.dead_at IS '超过重试上限进入 dead 状态的时间';

CREATE UNIQUE INDEX webhook_deliveries_event_endpoint_uq ON webhook_deliveries (workspace_id, outbox_event_id, webhook_endpoint_id);
CREATE INDEX webhook_deliveries_retry_idx ON webhook_deliveries (next_attempt_at, id) WHERE status IN ('pending', 'retrying');
CREATE INDEX webhook_deliveries_workspace_created_idx ON webhook_deliveries (workspace_id, created_at DESC, id DESC);

CREATE TABLE webhook_delivery_attempts (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    webhook_delivery_id uuid NOT NULL,
    attempt_no integer NOT NULL,
    target_url varchar(2048) NOT NULL,
    request_id varchar(100) NOT NULL,
    http_status integer,
    duration_ms integer,
    response_body varchar(8192),
    error_message varchar(2000),
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE webhook_delivery_attempts IS 'Webhook 投递每次 HTTP 尝试的受限明细';
COMMENT ON COLUMN webhook_delivery_attempts.id IS '投递尝试 UUID';
COMMENT ON COLUMN webhook_delivery_attempts.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN webhook_delivery_attempts.webhook_delivery_id IS 'Webhook 投递 UUID';
COMMENT ON COLUMN webhook_delivery_attempts.attempt_no IS '从 1 开始的尝试序号';
COMMENT ON COLUMN webhook_delivery_attempts.target_url IS '本次尝试的目标地址';
COMMENT ON COLUMN webhook_delivery_attempts.request_id IS '关联日志的请求 ID';
COMMENT ON COLUMN webhook_delivery_attempts.http_status IS '目标返回的 HTTP 状态码';
COMMENT ON COLUMN webhook_delivery_attempts.duration_ms IS '本次 HTTP 请求耗时毫秒数';
COMMENT ON COLUMN webhook_delivery_attempts.response_body IS '截断并脱敏后的响应体';
COMMENT ON COLUMN webhook_delivery_attempts.error_message IS '网络或协议错误摘要';
COMMENT ON COLUMN webhook_delivery_attempts.created_at IS '尝试时间';

CREATE UNIQUE INDEX webhook_delivery_attempts_delivery_no_uq ON webhook_delivery_attempts (webhook_delivery_id, attempt_no);
CREATE INDEX webhook_delivery_attempts_workspace_created_idx ON webhook_delivery_attempts (workspace_id, created_at DESC);

CREATE TABLE operation_runs (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    request_id varchar(100) NOT NULL,
    kind varchar(24) NOT NULL,
    name varchar(180) NOT NULL,
    status varchar(24) NOT NULL,
    system_id uuid,
    integration_id uuid,
    connection_id uuid,
    action_id uuid,
    sync_task_id uuid,
    runtime_token_id uuid,
    source varchar(32) NOT NULL,
    http_status integer,
    input jsonb,
    output jsonb,
    error_code varchar(120),
    error_message varchar(2000),
    started_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    expires_at timestamptz NOT NULL
);

COMMENT ON TABLE operation_runs IS 'Action、Sync、Webhook 和 Auth 的统一运行记录';
COMMENT ON COLUMN operation_runs.id IS '运行 UUID';
COMMENT ON COLUMN operation_runs.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN operation_runs.request_id IS '贯穿 HTTP、worker 和日志的请求 ID';
COMMENT ON COLUMN operation_runs.kind IS '运行类型，由应用校验 action、sync、webhook 或 auth';
COMMENT ON COLUMN operation_runs.name IS '页面显示的操作或任务名称快照';
COMMENT ON COLUMN operation_runs.status IS '运行状态，由应用校验 queued、running、success、failed 或 cancelled';
COMMENT ON COLUMN operation_runs.system_id IS '关联系统 UUID';
COMMENT ON COLUMN operation_runs.integration_id IS '关联集成 UUID';
COMMENT ON COLUMN operation_runs.connection_id IS '关联连接账号 UUID';
COMMENT ON COLUMN operation_runs.action_id IS '关联操作 UUID';
COMMENT ON COLUMN operation_runs.sync_task_id IS '关联同步任务 UUID';
COMMENT ON COLUMN operation_runs.runtime_token_id IS '发起运行的机器令牌 UUID';
COMMENT ON COLUMN operation_runs.source IS '触发来源，例如 api、manual、schedule 或 webhook';
COMMENT ON COLUMN operation_runs.http_status IS '外部系统或最终响应状态码';
COMMENT ON COLUMN operation_runs.input IS '脱敏且受大小限制的输入 JSON';
COMMENT ON COLUMN operation_runs.output IS '脱敏且受大小限制的输出 JSON';
COMMENT ON COLUMN operation_runs.error_code IS '稳定错误代码';
COMMENT ON COLUMN operation_runs.error_message IS '脱敏错误摘要';
COMMENT ON COLUMN operation_runs.started_at IS '开始时间';
COMMENT ON COLUMN operation_runs.completed_at IS '完成时间';
COMMENT ON COLUMN operation_runs.expires_at IS '按平台保留策略计算的清理时间';

CREATE UNIQUE INDEX operation_runs_workspace_request_uq ON operation_runs (workspace_id, request_id);
CREATE INDEX operation_runs_workspace_started_idx ON operation_runs (workspace_id, started_at DESC, id DESC);
CREATE INDEX operation_runs_filter_idx ON operation_runs (workspace_id, kind, status, started_at DESC);
CREATE INDEX operation_runs_connection_idx ON operation_runs (workspace_id, connection_id, started_at DESC) WHERE connection_id IS NOT NULL;

CREATE TABLE operation_events (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    operation_id uuid NOT NULL,
    sequence integer NOT NULL,
    level varchar(16) NOT NULL,
    message varchar(1000) NOT NULL,
    attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE operation_events IS '运行详情时间线中的结构化事件';
COMMENT ON COLUMN operation_events.id IS '运行事件 UUID';
COMMENT ON COLUMN operation_events.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN operation_events.operation_id IS '统一运行记录 UUID';
COMMENT ON COLUMN operation_events.sequence IS '运行内部严格递增的事件序号';
COMMENT ON COLUMN operation_events.level IS '日志级别，由应用校验 debug、info、warn 或 error';
COMMENT ON COLUMN operation_events.message IS '脱敏后的简短事件消息';
COMMENT ON COLUMN operation_events.attributes IS '不包含秘密的结构化上下文';
COMMENT ON COLUMN operation_events.created_at IS '事件时间';

CREATE UNIQUE INDEX operation_events_operation_sequence_uq ON operation_events (operation_id, sequence);
CREATE INDEX operation_events_workspace_created_idx ON operation_events (workspace_id, created_at DESC);

CREATE TABLE idempotency_records (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    runtime_token_id uuid NOT NULL,
    scope varchar(180) NOT NULL,
    idempotency_key varchar(255) NOT NULL,
    request_fingerprint char(64) NOT NULL,
    status varchar(24) NOT NULL,
    http_status integer,
    response jsonb,
    operation_id uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL
);

COMMENT ON TABLE idempotency_records IS '运行 API 的幂等占位与结果重放';
COMMENT ON COLUMN idempotency_records.id IS '幂等记录 UUID';
COMMENT ON COLUMN idempotency_records.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN idempotency_records.runtime_token_id IS '发起请求的运行时令牌 UUID';
COMMENT ON COLUMN idempotency_records.scope IS '操作标识或其他幂等作用域';
COMMENT ON COLUMN idempotency_records.idempotency_key IS '客户端提供的幂等键';
COMMENT ON COLUMN idempotency_records.request_fingerprint IS '规范化请求内容 SHA-256';
COMMENT ON COLUMN idempotency_records.status IS '状态，由应用校验 claimed 或 completed';
COMMENT ON COLUMN idempotency_records.http_status IS '可重放的 HTTP 状态码';
COMMENT ON COLUMN idempotency_records.response IS '脱敏且受大小限制的响应 envelope';
COMMENT ON COLUMN idempotency_records.operation_id IS '首次执行产生的运行 UUID';
COMMENT ON COLUMN idempotency_records.created_at IS '占位创建时间';
COMMENT ON COLUMN idempotency_records.expires_at IS '幂等记录过期时间';

CREATE UNIQUE INDEX idempotency_records_scope_key_uq ON idempotency_records (workspace_id, runtime_token_id, scope, idempotency_key);
CREATE INDEX idempotency_records_expiry_idx ON idempotency_records (expires_at);

CREATE TABLE audit_logs (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    request_id varchar(100) NOT NULL,
    actor_type varchar(24) NOT NULL,
    actor_id uuid,
    actor_label varchar(320) NOT NULL,
    action varchar(180) NOT NULL,
    resource_type varchar(80) NOT NULL,
    resource_id uuid,
    resource_label varchar(320),
    ip_address inet,
    before_data jsonb,
    after_data jsonb,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz
);

COMMENT ON TABLE audit_logs IS '控制面敏感变更审计日志';
COMMENT ON COLUMN audit_logs.id IS '审计事件 UUID';
COMMENT ON COLUMN audit_logs.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN audit_logs.request_id IS '关联 HTTP 请求 ID';
COMMENT ON COLUMN audit_logs.actor_type IS '操作者类型，由应用校验 user、admin_token、runtime_token 或 system';
COMMENT ON COLUMN audit_logs.actor_id IS '操作者资源 UUID';
COMMENT ON COLUMN audit_logs.actor_label IS '操作者名称或邮箱快照';
COMMENT ON COLUMN audit_logs.action IS '稳定审计动作，例如 member.role_updated';
COMMENT ON COLUMN audit_logs.resource_type IS '目标资源类型';
COMMENT ON COLUMN audit_logs.resource_id IS '目标资源 UUID';
COMMENT ON COLUMN audit_logs.resource_label IS '目标资源显示名称快照';
COMMENT ON COLUMN audit_logs.ip_address IS '客户端 IP';
COMMENT ON COLUMN audit_logs.before_data IS '变更前的脱敏字段';
COMMENT ON COLUMN audit_logs.after_data IS '变更后的脱敏字段';
COMMENT ON COLUMN audit_logs.metadata IS '请求来源等非敏感上下文';
COMMENT ON COLUMN audit_logs.created_at IS '审计事件时间';
COMMENT ON COLUMN audit_logs.expires_at IS '可选清理时间；永久保留时为空';

CREATE INDEX audit_logs_workspace_created_idx ON audit_logs (workspace_id, created_at DESC, id DESC);
CREATE INDEX audit_logs_resource_idx ON audit_logs (workspace_id, resource_type, resource_id, created_at DESC);
CREATE INDEX audit_logs_action_idx ON audit_logs (workspace_id, action, created_at DESC);

CREATE TABLE platform_settings (
    workspace_id uuid PRIMARY KEY,
    platform_name varchar(160) NOT NULL,
    public_base_url varchar(2048) NOT NULL,
    runtime_parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
    operation_retention_days integer NOT NULL DEFAULT 30,
    audit_retention_days integer,
    version bigint NOT NULL DEFAULT 1,
    updated_by uuid NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE platform_settings IS '平台常规设置、允许编辑的运行参数和数据保留策略';
COMMENT ON COLUMN platform_settings.workspace_id IS '所属工作区 UUID，同时作为主键';
COMMENT ON COLUMN platform_settings.platform_name IS '页面和通知使用的平台名称';
COMMENT ON COLUMN platform_settings.public_base_url IS 'OAuth 回调和公开链接使用的基础地址';
COMMENT ON COLUMN platform_settings.runtime_parameters IS '经过服务端白名单校验的运行参数，不允许任意进程环境变量';
COMMENT ON COLUMN platform_settings.operation_retention_days IS '运行日志保留天数';
COMMENT ON COLUMN platform_settings.audit_retention_days IS '审计日志保留天数；为空表示永久';
COMMENT ON COLUMN platform_settings.version IS '乐观锁版本号';
COMMENT ON COLUMN platform_settings.updated_by IS '最近修改用户 UUID';
COMMENT ON COLUMN platform_settings.updated_at IS '最后更新时间';

CREATE TABLE platform_secrets (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    secret_key varchar(100) NOT NULL,
    display_prefix varchar(32),
    secret_hash char(64),
    secret_blob bytea,
    key_version smallint NOT NULL DEFAULT 1,
    status varchar(24) NOT NULL,
    grace_expires_at timestamptz,
    last_used_at timestamptz,
    rotated_from_id uuid,
    created_by uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    revoked_at timestamptz
);

COMMENT ON TABLE platform_secrets IS '服务端密钥、公开标识和 Webhook 密钥的版本化保存';
COMMENT ON COLUMN platform_secrets.id IS '平台密钥 UUID';
COMMENT ON COLUMN platform_secrets.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN platform_secrets.secret_key IS '密钥用途，例如 server_key、public_key 或 webhook_signing_key';
COMMENT ON COLUMN platform_secrets.display_prefix IS '页面展示的非敏感密钥前缀';
COMMENT ON COLUMN platform_secrets.secret_hash IS '只需要校验而无需取回的密钥哈希';
COMMENT ON COLUMN platform_secrets.secret_blob IS '需要运行时取回的 AES-GCM 密文';
COMMENT ON COLUMN platform_secrets.key_version IS '加密主密钥版本';
COMMENT ON COLUMN platform_secrets.status IS '密钥状态，由应用校验 active、grace 或 revoked';
COMMENT ON COLUMN platform_secrets.grace_expires_at IS '轮换宽限期截止时间';
COMMENT ON COLUMN platform_secrets.last_used_at IS '最近使用时间';
COMMENT ON COLUMN platform_secrets.rotated_from_id IS '本版本替代的旧密钥 UUID';
COMMENT ON COLUMN platform_secrets.created_by IS '创建或轮换密钥的用户 UUID';
COMMENT ON COLUMN platform_secrets.created_at IS '创建时间';
COMMENT ON COLUMN platform_secrets.revoked_at IS '撤销时间';

CREATE INDEX platform_secrets_active_idx ON platform_secrets (workspace_id, secret_key, created_at DESC) WHERE revoked_at IS NULL;

CREATE TABLE metric_hourly (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    bucket_start timestamptz NOT NULL,
    kind varchar(24) NOT NULL,
    system_id uuid,
    action_id uuid,
    status varchar(24) NOT NULL,
    request_count bigint NOT NULL DEFAULT 0,
    success_count bigint NOT NULL DEFAULT 0,
    failure_count bigint NOT NULL DEFAULT 0,
    duration_sum_ms bigint NOT NULL DEFAULT 0,
    duration_max_ms integer NOT NULL DEFAULT 0,
    records_count bigint NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE metric_hourly IS '运行中心图表使用的小时级聚合事实';
COMMENT ON COLUMN metric_hourly.id IS '聚合行 UUID';
COMMENT ON COLUMN metric_hourly.workspace_id IS '所属工作区 UUID';
COMMENT ON COLUMN metric_hourly.bucket_start IS 'UTC 小时桶开始时间';
COMMENT ON COLUMN metric_hourly.kind IS '运行类型 action、sync、webhook 或 auth';
COMMENT ON COLUMN metric_hourly.system_id IS '可选系统维度 UUID';
COMMENT ON COLUMN metric_hourly.action_id IS '可选操作维度 UUID';
COMMENT ON COLUMN metric_hourly.status IS '聚合状态维度';
COMMENT ON COLUMN metric_hourly.request_count IS '总运行次数';
COMMENT ON COLUMN metric_hourly.success_count IS '成功次数';
COMMENT ON COLUMN metric_hourly.failure_count IS '失败次数';
COMMENT ON COLUMN metric_hourly.duration_sum_ms IS '总耗时毫秒数，用于计算平均耗时';
COMMENT ON COLUMN metric_hourly.duration_max_ms IS '最大耗时毫秒数';
COMMENT ON COLUMN metric_hourly.records_count IS '同步读取或写入的记录数量';
COMMENT ON COLUMN metric_hourly.updated_at IS '最近聚合更新时间';

CREATE UNIQUE INDEX metric_hourly_dimensions_uq ON metric_hourly (
    workspace_id,
    bucket_start,
    kind,
    (coalesce(system_id, '00000000-0000-0000-0000-000000000000'::uuid)),
    (coalesce(action_id, '00000000-0000-0000-0000-000000000000'::uuid)),
    status
);
CREATE INDEX metric_hourly_workspace_bucket_idx ON metric_hourly (workspace_id, bucket_start DESC);

INSERT INTO schema_migrations (version) VALUES (1);

COMMIT;
